name = "playjonny-opinie-pl"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-opinie.pl"
HMAC_KEY = "4c3216922b56a76b3eeeeac4e9f688f49caaaecb44c44a866192f7682a6338ac"
COOKIE_NAME = "0tn"
PLAY_PATH = "visit"
BUTTON_ID = "pbfd27f11a325f61057c9317eeda2adf2"
GATE_SALT = "dae25cee3b09d48a"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "2syn"
CTA_SELECTOR = ".play-button"
