name = "playjonny-opinie-pl"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-opinie.pl"
HMAC_KEY = "4c3216922b56a76b3eeeeac4e9f688f49caaaecb44c44a866192f7682a6338ac"
COOKIE_NAME = "yb2"
PLAY_PATH = "try-now"
BUTTON_ID = "pbfd27f11a325f61057c9317eeda2adf2"
GATE_SALT = "cc611edea8f7e9c5"
